name: starrail_app
description: A Discord-like chat application built with Flutter and Firebase.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.2.0

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4

  # Utilities 
  freezed_annotation: ^2.4.4
  uuid: ^4.4.0
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2

flutter:
  uses-material-design: true