// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmFJUe343Filv2VEmRyHvI2eBfGUc-QFs',
    appId: '1:352924430721:web:04bc45ee784b2d5ccb7880',
    messagingSenderId: '352924430721',
    projectId: 'starrail-app',
    authDomain: 'starrail-app.firebaseapp.com',
    storageBucket: 'starrail-app.firebasestorage.app',
    measurementId: 'G-NG62C56KQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs7IyF9lqn1cn0OUnMQnzrderdwcXgBFQ',
    appId: '1:352924430721:android:55a1ace6b632472ccb7880',
    messagingSenderId: '352924430721',
    projectId: 'starrail-app',
    storageBucket: 'starrail-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAybGvGYq-pM8n-xPPRYEKDEIps4kUKZdM',
    appId: '1:352924430721:ios:7103252f5a87fab1cb7880',
    messagingSenderId: '352924430721',
    projectId: 'starrail-app',
    storageBucket: 'starrail-app.firebasestorage.app',
    iosBundleId: 'com.example.starrailApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAybGvGYq-pM8n-xPPRYEKDEIps4kUKZdM',
    appId: '1:352924430721:ios:7103252f5a87fab1cb7880',
    messagingSenderId: '352924430721',
    projectId: 'starrail-app',
    storageBucket: 'starrail-app.firebasestorage.app',
    iosBundleId: 'com.example.starrailApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmFJUe343Filv2VEmRyHvI2eBfGUc-QFs',
    appId: '1:352924430721:web:4882dff21338720bcb7880',
    messagingSenderId: '352924430721',
    projectId: 'starrail-app',
    authDomain: 'starrail-app.firebaseapp.com',
    storageBucket: 'starrail-app.firebasestorage.app',
    measurementId: 'G-NYBPG5HTFM',
  );
}
